<?php 
$this->widget($this->getModule()->getClass('gridview'), array(
    'id'=>'payment_grid',
    'dataProvider' => $dataProvider,
    'template'=>'{items}',
    'columns'=>array(
        array(
            'class'=>'CLinkColumn',
            'header'=>Payment::model()->getAttributeLabel('payment_no'),
            'labelExpression'=>'$data->payment_no',
            'urlExpression'=>'$data->viewUrl',
            'htmlOptions'=>array('style'=>'text-align:center;'),
            'visible'=>user()->isAuthenticated,
        ),
        array(
            'header'=>Payment::model()->getAttributeLabel('payment_no'),
            'value'=>'$data->payment_no',
            'htmlOptions'=>array('style'=>'text-align:center;'),
            'visible'=>user()->isGuest,
        ),
        array(
            'name'=>'create_time',
            'value'=>'$data->formatDatetime($data->create_time,true)',
            'htmlOptions'=>array('style'=>'text-align:center'),
            'type'=>'html',
        ),
        array(
            'name'=>'type',
            'value'=>'$data->getTypeDesc()',
            'htmlOptions'=>array('style'=>'text-align:center'),
            'type'=>'html',
        ),
        array(
            'name'=>'method',
            'value'=>'$data->getPaymentMethodName(user()->getLocale())',
            'htmlOptions'=>array('style'=>'text-align:center'),
            'type'=>'html',
        ),
        array(
            'name'=>'amount',
            'value'=>'$data->formatCurrency($data->amount,$data->currency)',
            'htmlOptions'=>array('style'=>'text-align:center'),
            'type'=>'html',
        ),
        array(
            'name'=>'trace_no',
            'value'=>'$data->getTraceNo()',
            'htmlOptions'=>array('style'=>'color:burlywood'),
            'type'=>'html',
        ),
    ),
));