<?php 
 //this file is used in items module
$this->widget($this->getModule()->getClass('gridview'), array(
    'id'=>'order_summary_grid',
    'dataProvider'=>$dataProvider,
    'template'=>'{items}',
    'columns'=>array(
        array(
           'name'=>'create_time',
           'value'=>'$data->formatDatetime($data->create_time,true)',
           'htmlOptions'=>array('style'=>'text-align:center'),
           'type'=>'html',
        ),
        array(
           'name'=>'payment_method',
           'value'=>'$data->getPaymentMethodName(user()->getLocale())',
           'htmlOptions'=>array('style'=>'text-align:center'),
           'type'=>'html',
        ),
        array(
           'name'=>'item_total',
           'value'=>'$data->formatCurrency($data->item_total)',
           'htmlOptions'=>array('style'=>'text-align:center'),
           'type'=>'html',
        ),
        array(
           'name'=>'discount',
           'value'=>'$data->formatCurrency($data->getDiscountTotal())',
           'htmlOptions'=>array('style'=>'text-align:center'),
           'type'=>'raw',
        ),
        array(
           'name'=>'tax',
           'value'=>'$data->hasTax()?Helper::htmlList($data->getTaxDisplayText(user()->getLocale())):$data->formatCurrency(0)',
           'htmlOptions'=>array('style'=>'text-align:center'),
           'type'=>'raw',
        ),
        array(
           'name'=>'shipping_total',
           'value'=>'$data->formatShippingTotal($data->shipping_total,user()->getLocale())',
           'htmlOptions'=>array('style'=>'text-align:center'),
           'type'=>'html',
         ),
        array(
            'name'=>'grand_total',
            'value'=>'$data->formatCurrency($data->grand_total)',
            'htmlOptions'=>array('style'=>'text-align:center'),
            'type'=>'html',
        ),
    ),
)); 