#!/usr/bin/env php
<?php
/**
 * This file is part of Shopbay.org (https://shopbay.org)
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
/**
 * Environment Initialization Tool (for unix environment)
 *
 * @author kwlok
 */
function getInput($message)
{
    echo $message;
    $handle = fopen ("php://stdin","r");
    $input  = fgets($handle);
    fclose($handle);
    return trim($input);
}
function printOutput($output)
{
    if (!empty($output))
        print_r($output)."\n";
}

echo "--------------------------------------------\n";
echo "Shopbay Environment Initialization Tool v1.0\n";
echo "--------------------------------------------\n";
$appBasePath = dirname(__FILE__);
echo "App base path: ".$appBasePath."\n\n";

$userGroup = getInput('Please enter user group (e.g. _www or www-data) : ');

echo "[1] App base path permission setting\n";
echo " 1.1 restrict owner only to access app base path \n";
$output = shell_exec("chmod -R go-rwx ".$appBasePath);
printOutput($output);

echo " 1.2 grant exec for others \n";
$output = shell_exec("chmod -R go+x ".$appBasePath);
printOutput($output);

echo " 1.3 change group to ".$userGroup." \n";
$output = shell_exec("chgrp -R ".$userGroup." ".$appBasePath);
printOutput($output);

echo " 1.4 grant read/exec for group ".$userGroup." \n";
$output = shell_exec("chmod -R g+rx ".$appBasePath);
printOutput($output);

echo "\n";
echo "[2] App Permission setting\n";
echo " 2.1 grant write to group ".$userGroup." for following sub directories: \n";

//The sub directories to scan
$subdirs = [
    'runtime',
    'assets',
    'www/assets',
    'www/uploads',
    'www/files',
    'modules/*/assets',
];

foreach ($subdirs as $subdir) {
    $path = $appBasePath."/".$subdir;
    echo " ".$path."\n";
    $output = shell_exec("chmod -R g+w ".$path);
    printOutput($output);

}

echo "\n** end **\n";

